# Limine Configuration File
# Orizon OS x86_64

# Timeout before autoboot (seconds)
timeout: 5

# Default boot entry
default_entry: 1

# ==========================================
# Orizon OS x86_64
# ==========================================

/Orizon OS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: orizon-bootx64
