# Limine Configuration File
# Orizon OS

# Timeout before autoboot (seconds)
timeout: 5

# Default boot entry
default_entry: 1

# ==========================================
# Orizon OS
# ==========================================

/Orizon OS
    protocol: limine
    kernel_path: boot():/boot/orizonos.elf
