# Limine Configuration File
# Orizon OS x86_64

# Timeout before autoboot (seconds)
timeout: 5
interface_resolution: 1024x768
interface_branding: Orizon OS

# Default boot entry
default_entry: 1

# ==========================================
# Orizon OS x86_64
# ==========================================

/Orizon OS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: orizon.safe=1
    resolution: 1024x768x32
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: orizon-bootx64

/Orizon OS - Lenovo hardware probe
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: orizon.i2chid=1
    resolution: 1024x768x32
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: orizon-bootx64

/Orizon OS - Native display
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: orizon.native=1
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: orizon-bootx64
