/*
 * Orizon OS x86_64 - Wi-Fi hardware detection and driver staging
 */

#ifndef _WIFI_H
#define _WIFI_H

#include "types.h"

#define WIFI_SCAN_RESULT_SLOTS 8U
#define WIFI_SCAN_AP_SLOTS 8U
#define WIFI_SCAN_SSID_MAX 32U
#define WIFI_SCAN_CANDIDATE_SLOTS 8U
#define WIFI_SCAN_DEBUG_BYTES 32U

typedef struct {
  int present;
  int driver_ready;
  int associated;
  uint8_t bus;
  uint8_t device;
  uint8_t function;
  uint16_t vendor_id;
  uint16_t device_id;
  int mmio_probed;
  int mmio_ready;
  uint64_t mmio_phys;
  uint32_t pci_command;
  uint32_t csr_hw_if_config;
  uint32_t csr_hw_rev;
  uint32_t csr_hw_rf_id;
  uint32_t csr_gp_cntrl;
  uint32_t csr_gpio_in;
  uint32_t csr_reset;
  uint32_t csr_int;
  uint32_t csr_int_mask;
  uint32_t csr_fh_int_status;
  unsigned long mmio_errors;
  int apm_ready;
  int apm_timeout;
  unsigned long apm_attempts;
  uint32_t apm_poll_ready_mask;
  uint32_t apm_last_gp;
  uint32_t apm_last_hw_if;
  uint32_t apm_last_gio;
  uint32_t apm_last_hpet;
  int alive_seen;
  int alive_timeout;
  unsigned long alive_polls;
  unsigned long alive_errors;
  uint32_t alive_last_csr_int;
  uint32_t alive_last_fh_int;
  uint32_t alive_last_gp;
  int boot_ready;
  int boot_released;
  int boot_failed;
  unsigned long boot_attempts;
  unsigned long boot_cpu1_sections;
  unsigned long boot_cpu2_sections;
  unsigned long boot_paging_sections_skipped;
  unsigned long boot_sections_loaded;
  uint32_t boot_release_value;
  uint32_t boot_fh_status;
  uint32_t boot_ureg_status;
  uint32_t boot_first_cpu2_index;
  uint32_t boot_paging_index;
  uint32_t boot_last_gp;
  int queues_ready;
  int queues_armed;
  int queues_failed;
  unsigned long queue_errors;
  unsigned long queue_generation;
  unsigned long cmd_queue_entries;
  unsigned long tx_queue_entries;
  unsigned long rx_queue_entries;
  unsigned long cmd_buffer_bytes;
  unsigned long tx_buffer_bytes;
  unsigned long rx_buffer_bytes;
  unsigned long cmd_tfd_bytes;
  unsigned long tx_tfd_bytes;
  unsigned long rx_desc_bytes;
  uint64_t cmd_tfd_phys;
  uint64_t cmd_buffer_phys;
  uint64_t tx_tfd_phys;
  uint64_t tx_buffer_phys;
  uint64_t rx_desc_phys;
  uint64_t rx_used_desc_phys;
  uint64_t rx_status_phys;
  uint64_t rx_buffer_phys;
  uint32_t cmd_write_ptr;
  uint32_t tx_write_ptr;
  uint32_t rx_write_ptr;
  int context_ready;
  int context_armed;
  int context_failed;
  uint32_t context_mode;
  unsigned long context_errors;
  unsigned long context_generation;
  unsigned long context_lmac_sections;
  unsigned long context_umac_sections;
  unsigned long context_paging_sections;
  uint64_t legacy_context_phys;
  uint64_t v2_context_phys;
  uint64_t prph_info_phys;
  uint64_t prph_scratch_phys;
  uint32_t context_size;
  uint32_t context_v2_size;
  uint32_t prph_scratch_size;
  uint32_t context_control_flags;
  uint32_t context_v2_control_flags;
  uint32_t context_csr_target;
  uint32_t context_csr_value_lo;
  uint32_t context_csr_value_hi;
  int scheduler_ready;
  int scheduler_armed;
  int scheduler_failed;
  unsigned long scheduler_errors;
  unsigned long scheduler_generation;
  uint64_t cmd_bc_phys;
  uint64_t tx_bc_phys;
  uint64_t mtr_ring_phys;
  uint64_t mcr_ring_phys;
  uint64_t cr_head_phys;
  uint64_t cr_tail_phys;
  uint64_t tr_head_phys;
  uint64_t tr_tail_phys;
  uint32_t mtr_entries;
  uint32_t mcr_entries;
  uint32_t msg_ring_bytes;
  uint32_t scheduler_cmd_id;
  uint32_t scheduler_cmd_group;
  uint32_t scheduler_cmd_version;
  uint32_t scheduler_cmd_len;
  uint32_t scheduler_cmd_sequence;
  uint32_t scheduler_cmd_queue;
  uint32_t scheduler_cmd_index;
  uint32_t scheduler_cmd_tbs;
  uint32_t scheduler_cmd_tb_len;
  uint32_t scheduler_wptr_value;
  int rx_path_ready;
  int rx_path_failed;
  unsigned long rx_path_errors;
  unsigned long rx_polls;
  unsigned long rx_packets;
  uint32_t rx_closed_rb;
  uint32_t rx_read_ptr;
  uint32_t rx_last_rbid;
  uint32_t rx_last_flags;
  uint32_t rx_last_len_n_flags;
  uint32_t rx_last_len;
  uint32_t rx_last_queue;
  uint32_t rx_last_cmd;
  uint32_t rx_last_group;
  uint32_t rx_last_sequence;
  uint32_t rx_last_index;
  uint32_t rx_last_word0;
  uint32_t rx_last_word1;
  uint32_t rx_last_word2;
  uint32_t rx_last_word3;
  uint32_t rx_last_cd_word0;
  uint32_t rx_last_cd_word1;
  uint32_t rx_last_cd_word2;
  uint32_t rx_last_cd_word3;
  int command_ready;
  int command_sent;
  int command_failed;
  int command_response_seen;
  int command_timeout;
  unsigned long command_attempts;
  unsigned long command_errors;
  uint32_t command_doorbell_value;
  uint32_t command_wptr_readback;
  uint32_t command_bc_entry;
  uint32_t command_tfd_num_tbs;
  uint32_t command_tfd_tb0_len;
  uint64_t command_tfd_tb0_addr;
  uint32_t command_before_csr_int;
  uint32_t command_before_fh_int;
  uint32_t command_before_closed_rb;
  uint32_t command_before_read_ptr;
  uint32_t command_after_csr_int;
  uint32_t command_after_fh_int;
  uint32_t command_after_closed_rb;
  uint32_t command_after_read_ptr;
  uint32_t command_last_csr_int;
  uint32_t command_last_fh_int;
  uint32_t command_last_closed_rb;
  uint32_t command_poll_loops;
  int nvm_ready;
  int nvm_failed;
  int nvm_response_seen;
  unsigned long nvm_errors;
  unsigned long nvm_generation;
  uint32_t nvm_op;
  uint32_t nvm_target;
  uint32_t nvm_section;
  uint32_t nvm_offset;
  uint32_t nvm_length;
  uint32_t nvm_resp_offset;
  uint32_t nvm_resp_length;
  uint32_t nvm_resp_type;
  uint32_t nvm_resp_status;
  uint32_t nvm_resp_word0;
  uint32_t nvm_resp_word1;
  uint32_t nvm_resp_word2;
  uint32_t nvm_resp_word3;
  int nvm_info_ready;
  int nvm_info_failed;
  int nvm_info_response_seen;
  unsigned long nvm_info_errors;
  unsigned long nvm_info_generation;
  uint32_t nvm_info_flags;
  uint32_t nvm_info_version;
  uint32_t nvm_info_board_type;
  uint32_t nvm_info_hw_addrs;
  uint32_t nvm_info_mac_sku_flags;
  uint32_t nvm_info_tx_chains;
  uint32_t nvm_info_rx_chains;
  uint32_t nvm_info_lar_enabled;
  uint32_t nvm_info_n_channels;
  int scan_ready;
  int scan_failed;
  int scan_response_seen;
  int scan_start_seen;
  int scan_iter_seen;
  int scan_complete_seen;
  int scan_inflight;
  unsigned long scan_errors;
  unsigned long scan_generation;
  unsigned long scan_notifications;
  uint32_t scan_uid;
  uint32_t scan_cmd_len;
  uint32_t scan_version;
  uint32_t scan_flags;
  uint32_t scan_general_flags;
  uint32_t scan_channel_count;
  uint32_t scan_channel_first;
  uint32_t scan_channel_last;
  uint32_t scan_dwell_active;
  uint32_t scan_dwell_passive;
  uint32_t scan_start_uid;
  uint32_t scan_iter_uid;
  uint32_t scan_iter_channels;
  uint32_t scan_iter_status;
  uint32_t scan_iter_bt_status;
  uint32_t scan_iter_last_channel;
  uint32_t scan_iter_tsf_low;
  uint32_t scan_iter_tsf_high;
  uint32_t scan_complete_uid;
  uint32_t scan_complete_last_schedule;
  uint32_t scan_complete_last_iter;
  uint32_t scan_complete_status;
  uint32_t scan_complete_ebs_status;
  uint32_t scan_complete_elapsed;
  int scan_result_truncated;
  uint32_t scan_result_count;
  uint32_t scan_result_reported;
  uint32_t scan_result_entries;
  uint32_t scan_result_bytes;
  uint32_t scan_result_channel[WIFI_SCAN_RESULT_SLOTS];
  uint32_t scan_result_band[WIFI_SCAN_RESULT_SLOTS];
  uint32_t scan_result_probe_status[WIFI_SCAN_RESULT_SLOTS];
  uint32_t scan_result_probe_not_sent[WIFI_SCAN_RESULT_SLOTS];
  uint32_t scan_result_duration[WIFI_SCAN_RESULT_SLOTS];
  unsigned long scan_mpdu_packets;
  unsigned long scan_mgmt_frames;
  unsigned long scan_beacon_frames;
  unsigned long scan_probe_resp_frames;
  unsigned long scan_ssid_updates;
  unsigned long scan_mpdu_parse_misses;
  uint32_t scan_last_mpdu_payload_len;
  uint32_t scan_last_mpdu_len;
  uint32_t scan_last_frame_offset;
  uint32_t scan_last_frame_len;
  uint32_t scan_last_frame_control;
  uint32_t scan_last_frame_subtype;
  uint32_t scan_last_frame_channel;
  uint32_t scan_last_debug_len;
  uint8_t scan_last_debug_bytes[WIFI_SCAN_DEBUG_BYTES];
  uint32_t scan_candidate_count;
  uint32_t scan_candidate_offset[WIFI_SCAN_CANDIDATE_SLOTS];
  uint32_t scan_candidate_len[WIFI_SCAN_CANDIDATE_SLOTS];
  uint32_t scan_candidate_fc[WIFI_SCAN_CANDIDATE_SLOTS];
  uint32_t scan_candidate_type[WIFI_SCAN_CANDIDATE_SLOTS];
  uint32_t scan_candidate_subtype[WIFI_SCAN_CANDIDATE_SLOTS];
  uint32_t scan_ap_count;
  uint32_t scan_ap_overflow;
  uint32_t scan_ap_channel[WIFI_SCAN_AP_SLOTS];
  uint32_t scan_ap_frame_subtype[WIFI_SCAN_AP_SLOTS];
  uint32_t scan_ap_seen_count[WIFI_SCAN_AP_SLOTS];
  uint32_t scan_ap_ssid_len[WIFI_SCAN_AP_SLOTS];
  uint8_t scan_ap_bssid[WIFI_SCAN_AP_SLOTS][6];
  char scan_ap_ssid[WIFI_SCAN_AP_SLOTS][WIFI_SCAN_SSID_MAX + 1U];
  const char *chipset;
  const char *driver;
  const char *status;
  int firmware_present;
  int firmware_valid;
  size_t firmware_size;
  uint32_t firmware_version;
  uint32_t firmware_build;
  unsigned long firmware_tlv_count;
  unsigned long firmware_inst_bytes;
  unsigned long firmware_data_bytes;
  unsigned long firmware_section_count;
  unsigned long firmware_runtime_sections;
  unsigned long firmware_init_sections;
  unsigned long firmware_wowlan_sections;
  unsigned long firmware_secure_sections;
  unsigned long firmware_load_bytes;
  unsigned long firmware_load_chunks;
  unsigned long firmware_largest_section;
  unsigned long firmware_api_count;
  unsigned long firmware_capa_count;
  unsigned long firmware_parse_errors;
  uint32_t firmware_cpu_count;
  uint32_t firmware_first_dst;
  int firmware_load_plan_ready;
  char firmware_human[65];
  const char *firmware_name;
  const char *firmware_source;
  int dma_ready;
  uint64_t dma_phys;
  unsigned long dma_chunk_bytes;
  unsigned long dma_staged_bytes;
  unsigned long firmware_load_attempts;
  int fh_plan_ready;
  int fh_armed;
  int fh_complete;
  int fh_timeout;
  unsigned long fh_errors;
  uint32_t fh_channel;
  uint32_t fh_dst_addr;
  uint32_t fh_byte_count;
  uint32_t fh_ctrl0_value;
  uint32_t fh_ctrl1_value;
  uint32_t fh_buf_status_value;
  uint32_t fh_tx_config_value;
  uint32_t fh_last_csr_int;
  uint32_t fh_last_fh_int;
  uint32_t fh_last_tx_status;
  uint32_t fh_last_tx_error;
  unsigned long fh_total_chunks;
  unsigned long fh_uploaded_chunks;
  unsigned long fh_uploaded_bytes;
  unsigned long fh_sections_done;
  uint32_t fh_last_section;
  uint32_t fh_last_offset;
  uint32_t fh_last_len;
  int fh_all_plan_ready;
  const char *load_state;
} wifi_status_t;

int wifi_init(void);
void wifi_poll(void);
const wifi_status_t *wifi_get_status(void);
void wifi_format_status(char *buf, size_t size);
int wifi_firmware_probe(char *report, size_t report_size);
int wifi_hw_probe(char *report, size_t report_size);
int wifi_apm_probe(char *report, size_t report_size);
int wifi_load_firmware(char *report, size_t report_size);
int wifi_upload_firmware(int arm, char *report, size_t report_size);
int wifi_upload_all_firmware(int arm, char *report, size_t report_size);
int wifi_boot_firmware(int arm, char *report, size_t report_size);
int wifi_alive_probe(char *report, size_t report_size);
int wifi_queue_probe(int arm, char *report, size_t report_size);
int wifi_context_probe(int arm, char *report, size_t report_size);
int wifi_scheduler_probe(int arm, char *report, size_t report_size);
int wifi_rx_probe(int poll, char *report, size_t report_size);
int wifi_command_probe(int arm, char *report, size_t report_size);
int wifi_nvm_probe(int arm, char *report, size_t report_size);
int wifi_nvm_info_probe(int arm, char *report, size_t report_size);
int wifi_bringup_probe(char *report, size_t report_size);
int wifi_scan(int arm, char *report, size_t report_size);
int wifi_scan_poll(char *report, size_t report_size);
int wifi_connect(const char *ssid, const char *password, char *report,
                 size_t report_size);

#endif /* _WIFI_H */
